export const tehnologija = {
    category: "Tehnologija",
    items: [
        { word: "JavaScript", hint: "TypeScript" },
        { word: "Monitor", hint: "Televizor" },
        { word: "Laptop", hint: "Tablet" },
        { word: "Miš", hint: "Tastatura" },
        { word: "Slušalice", hint: "Zvučnici" },
        { word: "Vajber", hint: "WhatsApp" },
        { word: "Instagram", hint: "TikTok" },
        { word: "Google", hint: "ChatGPT" },
        { word: "PlayStation", hint: "Xbox" },
        { word: "Wi-Fi", hint: "Bluetooth" },
        { word: "Hard disk", hint: "USB fleš" },
        { word: "Punjač", hint: "Baterija" },
        { word: "Kamera", hint: "Oko" },
        { word: "Windows", hint: "Linux" },
        { word: "Steam", hint: "Epic Games" },
        { word: "Procesor", hint: "Grafička karta" },
        { word: "Sajt", hint: "Aplikacija" },
        { word: "Šifra", hint: "PIN kod" },
        { word: "Selfi", hint: "Portret" },
        { word: "E-mail", hint: "SMS" },
        { word: "Bitkoin", hint: "NFT" },
        { word: "Router", hint: "Modem" },
        { word: "Smartwatch", hint: "Narukvica za fitness" },
        { word: "Podcast", hint: "Radio" },
        { word: "Emoji", hint: "Nalepnica (Sticker)" },
        { word: "Update", hint: "Upgrade" },
        { word: "Bug", hint: "Feature" },
        { word: "Haker", hint: "Programer" },
        { word: "Folder", hint: "Fajl" },
        { word: "Desktop", hint: "Laptop" },
        { word: "Cloud", hint: "Server" },
        { word: "VPN", hint: "Proxy" },
        { word: "Inkognito mod", hint: "Privatni tab" },
        { word: "Ekran", hint: "Staklo" },
        { word: "Ikona", hint: "Prečica" },
        { word: "Zubčanik (Settings)", hint: "Lupa (Search)" },
        { word: "Kabl", hint: "Adapter" },
        { word: "Mikrofon", hint: "Diktafon" },
        { word: "Skeniranje", hint: "Štampanje" },
        { word: "Photoshop", hint: "Filter" },
        { word: "YouTube", hint: "Netflix" },
        { word: "Facebook", hint: "LinkedIn" },
        { word: "Reddit", hint: "Forum" },
        { word: "Dark mode", hint: "Noćno svetlo" },
        { word: "Touchscreen", hint: "Dugme" },
        { word: "Antivirus", hint: "Firewall" },
        { word: "Kalkulator", hint: "Excel" },
        { word: "Spotify", hint: "Deezer" },
        { word: "Kindle", hint: "Knjiga" },
        { word: "Powerbank", hint: "Agregat" }
    ]
};

export const hranaIPice = {
    category: "Hrana i piće",
    items: [
        { word: "Pljeskavica", hint: "Ćevapi" },
        { word: "Burek", hint: "Pita sa sirom" },
        { word: "Koka-kola", hint: "Pepsi" },
        { word: "Espreso", hint: "Domaća kafa" },
        { word: "Pivo", hint: "Vino" },
        { word: "Ketchup", hint: "Majonez" },
        { word: "Pica", hint: "Sendvič" },
        { word: "Jabuka", hint: "Kruška" },
        { word: "Limunada", hint: "Narandža" },
        { word: "Čokolada", hint: "Keks" }
    ]
};

export const zivotinje = {
    category: "Životinje",
    items: [
        { word: "Lav", hint: "Tigar" },
        { word: "Vuk", hint: "Pas" }, 
        { word: "Žirafa", hint: "Konj" },
        { word: "Ajkula", hint: "Delfin" },
        { word: "Pingvin", hint: "Noj" },
        { word: "Zmija", hint: "Gušter" },
        { word: "Pčela", hint: "Osa" },
        { word: "Slon", hint: "Nosorog" },
        { word: "Orao", hint: "Soko" },
        { word: "Mačka", hint: "Panter" },
        { word: "Krava", hint: "Ovca" },
        { word: "Koza", hint: "Srna" },
        { word: "Zec", hint: "Veverica" },
        { word: "Svinja", hint: "Vepar" },
        { word: "Kokoška", hint: "Ćurka" },
        { word: "Patka", hint: "Guska" },
        { word: "Miš", hint: "Pacov" },
        { word: "Krokodil", hint: "Aligator" },
        { word: "Majmun", hint: "Gorila" },
        { word: "Kit", hint: "Orka" },
        { word: "Komarac", hint: "Muva" },
        { word: "Mrav", hint: "Termit" },
        { word: "Pauk", hint: "Škorpija" },
        { word: "Leptir", hint: "Moljac" },
        { word: "Sova", hint: "Netopir" },
        { word: "Lisica", hint: "Šakal" },
        { word: "Medved", hint: "Panda" },
        { word: "Kamila", hint: "Lama" },
        { word: "Kengur", hint: "Valabi" },
        { word: "Zebra", hint: "Magarac" },
        { word: "Hrčak", hint: "Morsko prase" },
        { word: "Papagaj", hint: "Kanarinac" },
        { word: "Vrana", hint: "Gavran" },
        { word: "Labud", hint: "Pelikan" },
        { word: "Rak", hint: "Jastog" },
        { word: "Hobotnica", hint: "Lignja" },
        { word: "Žaba", hint: "Krastava žaba" },
        { word: "Kornjača", hint: "Puž" },
        { word: "Jelen", hint: "Los" },
        { word: "Bivo", hint: "Bik" }
    ]
};

export default [tehnologija, hranaIPice, zivotinje];
