export const tehnologija = {
    category: "Tehnologija",
    items: [
        { word: "JavaScript", hint: "Konzola" },
        { word: "Monitor", hint: "Piksel" },
        { word: "Laptop", hint: "Poklopac" },
        { word: "Miš", hint: "Kursor" },
        { word: "Slušalice", hint: "Izolacija" },
        { word: "Vajber", hint: "Kvačica" },
        { word: "Instagram", hint: "Rolna" },
        { word: "Google", hint: "Pretraga" },
        { word: "PlayStation", hint: "Džojstik" },
        { word: "Wi-Fi", hint: "Signal" },
        { word: "Hard disk", hint: "Skladište" },
        { word: "Punjač", hint: "Procenat" },
        { word: "Kamera", hint: "Objektiv" },
        { word: "Windows", hint: "Plavi ekran" },
        { word: "Steam", hint: "Biblioteka" },
        { word: "Procesor", hint: "Čip" },
        { word: "Sajt", hint: "Domen" },
        { word: "Šifra", hint: "Zvezdice" },
        { word: "Selfi", hint: "Ogledalo" },
        { word: "E-mail", hint: "Inbox" },
        { word: "Bitkoin", hint: "Rudarenje" },
        { word: "Router", hint: "Lampice" },
        { word: "Smartwatch", hint: "Zglob" },
        { word: "Podcast", hint: "Epizoda" },
        { word: "Emoji", hint: "Žuto lice" },
        { word: "Update", hint: "Čekanje" },
        { word: "Bug", hint: "Insekt" },
        { word: "Haker", hint: "Kapuljača" },
        { word: "Folder", hint: "Fascikla" },
        { word: "Cloud", hint: "Oblak" },
        { word: "VPN", hint: "Tunel" },
        { word: "Inkognito mod", hint: "Maska" },
        { word: "Kabl", hint: "Žica" },
        { word: "Mikrofon", hint: "Šum" },
        { word: "Photoshop", hint: "Slojevi" },
        { word: "YouTube", hint: "Pretplata" },
        { word: "Facebook", hint: "Zid" },
        { word: "Reddit", hint: "Karma" },
        { word: "Dark mode", hint: "Tema" },
        { word: "Touchscreen", hint: "Otisak" },
        { word: "Antivirus", hint: "Karantin" },
        { word: "Spotify", hint: "Plejlista" },
        { word: "Kindle", hint: "Stranica" },
        { word: "Powerbank", hint: "Rezerva" },
        { word: "Skener", hint: "Kopija" },
        { word: "Printer", hint: "Toner" },
        { word: "SSD", hint: "Brzina" },
        { word: "Dron", hint: "Propeler" },
        { word: "QR kod", hint: "Šara" },
        { word: "Algoritam", hint: "Recept" }
    ]
};

export const hranaIPice = {
    category: "Hrana i piće",
    items: [
        { word: "Pljeskavica", hint: "Somun" },
        { word: "Burek", hint: "Spirala" },
        { word: "Koka-kola", hint: "Mehurići" },
        { word: "Espreso", hint: "Gorčina" },
        { word: "Pivo", hint: "Pena" },
        { word: "Ketchup", hint: "Bočica" },
        { word: "Pica", hint: "Trougao" },
        { word: "Jabuka", hint: "Gren" },
        { word: "Limunada", hint: "Osveženje" },
        { word: "Čokolada", hint: "Kocka" },
        { word: "Palačinke", hint: "Namaz" },
        { word: "Sladoled", hint: "Kornet" },
        { word: "Pomfrit", hint: "Štapić" },
        { word: "Sarma", hint: "Rolnica" },
        { word: "Gibanica", hint: "Slojevi" },
        { word: "Jogurt", hint: "Kultura" },
        { word: "Banana", hint: "Ljuska" },
        { word: "Paradajz", hint: "Salata" },
        { word: "Krompir", hint: "Krtola" },
        { word: "Pirinač", hint: "Zrno" },
        { word: "Testenina", hint: "Al dente" },
        { word: "Hleb", hint: "Korica" },
        { word: "Jaje", hint: "Ljuska" },
        { word: "Šećer", hint: "Kristal" },
        { word: "So", hint: "Granula" },
        { word: "Torta", hint: "Svećica" },
        { word: "Krofna", hint: "Rupa" },
        { word: "Džem", hint: "Teglica" },
        { word: "Suši", hint: "Štapići" },
        { word: "Kebab", hint: "Ražanj" },
        { word: "Musaka", hint: "Zapečeno" },
        { word: "Čorba", hint: "Kašika" },
        { word: "Gulaš", hint: "Lonac" },
        { word: "Roštilj", hint: "Ćumur" },
        { word: "Viršla", hint: "Pecivo" },
        { word: "Sir", hint: "Rupe" },
        { word: "Lubenica", hint: "Semenke" },
        { word: "Jagoda", hint: "Šlag" },
        { word: "Kikiriki", hint: "Stadion" },
        { word: "Rakija", hint: "Zdravica" },
        { word: "Viski", hint: "Kocka leda" },
        { word: "Čaj", hint: "Kesica" },
        { word: "Kakao", hint: "Vrelo" },
        { word: "Smuti", hint: "Blender" },
        { word: "Ajvar", hint: "Jesen" },
        { word: "Ćevapi", hint: "Desetka" },
        { word: "Baklava", hint: "Sirup" },
        { word: "Pršut", hint: "Listić" },
        { word: "Kajmak", hint: "Namaz" },
        { word: "Kafa", hint: "Jutro" }
    ]
};

export const zivotinje = {
    category: "Životinje",
    items: [
        { word: "Lav", hint: "Griva" },
        { word: "Vuk", hint: "Čopor" },
        { word: "Žirafa", hint: "Horizont" },
        { word: "Ajkula", hint: "Peraje" },
        { word: "Pingvin", hint: "Smoking" },
        { word: "Zmija", hint: "Stepenice" },
        { word: "Pčela", hint: "Saće" },
        { word: "Slon", hint: "Pamćenje" },
        { word: "Orao", hint: "Grb" },
        { word: "Mačka", hint: "Devet života" },
        { word: "Krava", hint: "Livada" },
        { word: "Koza", hint: "Stena" },
        { word: "Zec", hint: "Cilindar" },
        { word: "Svinja", hint: "Kasica" },
        { word: "Kokoška", hint: "Zora" },
        { word: "Patka", hint: "Jezero" },
        { word: "Miš", hint: "Zamka" },
        { word: "Krokodil", hint: "Suze" },
        { word: "Majmun", hint: "Grimasa" },
        { word: "Kit", hint: "Dubina" },
        { word: "Komarac", hint: "Letnja noć" },
        { word: "Mrav", hint: "Kolona" },
        { word: "Pauk", hint: "Mreža" },
        { word: "Leptir", hint: "Efekat" },
        { word: "Sova", hint: "Mudrost" },
        { word: "Lisica", hint: "Lukavstvo" },
        { word: "Medved", hint: "Brlog" },
        { word: "Kamila", hint: "Oaza" },
        { word: "Kengur", hint: "Džep" },
        { word: "Zebra", hint: "Prelaz" },
        { word: "Hrčak", hint: "Točkić" },
        { word: "Papagaj", hint: "Ponavljanje" },
        { word: "Vrana", hint: "Strašilo" },
        { word: "Labud", hint: "Jezero" },
        { word: "Hobotnica", hint: "Mastilo" },
        { word: "Žaba", hint: "Princ" },
        { word: "Kornjača", hint: "Oklop" },
        { word: "Jelen", hint: "Trofej" },
        { word: "Pas", hint: "Vernost" },
        { word: "Hijena", hint: "Smeh" },
        { word: "Leopard", hint: "Šara" },
        { word: "Vidra", hint: "Potok" },
        { word: "Flamingo", hint: "Ravnoteža" },
        { word: "Foka", hint: "Aplauza" },
        { word: "Koala", hint: "Drvo" },
        { word: "Kameleon", hint: "Pozadina" },
        { word: "Galeb", hint: "Obala" },
        { word: "Delfin", hint: "Inteligencija" },
        { word: "Panda", hint: "Bambus" },
        { word: "Jež", hint: "Bodlje" }
    ]
};

export const sport = {
    category: "Sport",
    items: [
        { word: "Fudbal", hint: "Gol" },
        { word: "Košarka", hint: "Koš" },
        { word: "Tenis", hint: "Mreža" },
        { word: "Plivanje", hint: "Staza" },
        { word: "Atletika", hint: "Startni blok" },
        { word: "Boks", hint: "Gong" },
        { word: "Džudo", hint: "Pojas" },
        { word: "Hokej", hint: "Led" },
        { word: "Golf", hint: "Rupa" },
        { word: "Skijanje", hint: "Nanogice" },
        { word: "Biciklizam", hint: "Pedala" },
        { word: "Veslanje", hint: "Veslo" },
        { word: "Streljaštvo", hint: "Meta" },
        { word: "Rvanje", hint: "Zahvat" },
        { word: "Šah", hint: "Potez" },
        { word: "Bilijar", hint: "Zelena" },
        { word: "Bowling", hint: "Čunjevi" },
        { word: "Surfing", hint: "Talas" },
        { word: "Gimnastika", hint: "Greda" },
        { word: "Ragbi", hint: "Oval" },
        { word: "Stoni tenis", hint: "Loptice" },
        { word: "Maraton", hint: "Izdržljivost" },
        { word: "Formula 1", hint: "Boks" },
        { word: "Paraglajding", hint: "Strujanje" },
        { word: "Mačevanje", hint: "Maska" },
        { word: "Ronjenje", hint: "Boca" },
        { word: "Joga", hint: "Lotos" },
        { word: "Odbojka", hint: "Peščana" },
        { word: "Vaterpolo", hint: "Kapica" },
        { word: "Klizanje", hint: "Sečivo" },
        { word: "Kanu", hint: "Brzak" },
        { word: "Skejtbording", hint: "Rampa" },
        { word: "Bejzbol", hint: "Baza" },
        { word: "Pecanje", hint: "Strpljenje" },
        { word: "Darts", hint: "Centar" },
        { word: "E-sport", hint: "Arena" },
        { word: "Karate", hint: "Daska" },
        { word: "Kros", hint: "Blato" },
        { word: "Snowboard", hint: "Nišan" },
        { word: "Streličarstvo", hint: "Tetiva" },
        { word: "Badminton", hint: "Perjanica" },
        { word: "Kriket", hint: "Travnjak" },
        { word: "Polo", hint: "Čekić" },
        { word: "Trampolin", hint: "Odskok" },
        { word: "Dizanje tegova", hint: "Diskovi" },
        { word: "Aikido", hint: "Harmonija" },
        { word: "Biatlon", hint: "Kombinacija" },
        { word: "Kuglanje", hint: "Oluk" },
        { word: "Taekwondo", hint: "Kriik" },
        { word: "Sprint", hint: "Eksplozija" }
    ]
};

export const filmoviISerije = {
    category: "Filmovi i serije",
    items: [
        { word: "Harry Potter", hint: "Štapić" },
        { word: "Avengers", hint: "Okupljanje" },
        { word: "Star Wars", hint: "Svetlosni mač" },
        { word: "Batman", hint: "Pećina" },
        { word: "Spider-Man", hint: "Paučina" },
        { word: "Joker", hint: "Karta" },
        { word: "Titanic", hint: "Ledeni breg" },
        { word: "Matrix", hint: "Pilula" },
        { word: "Forrest Gump", hint: "Klupa" },
        { word: "Gladijator", hint: "Arena" },
        { word: "Shrek", hint: "Močvara" },
        { word: "Kralj lavova", hint: "Krug" },
        { word: "Ledeno doba", hint: "Žir" },
        { word: "Finding Nemo", hint: "Akvarium" },
        { word: "Toy Story", hint: "Igračka" },
        { word: "Frozen", hint: "Snežna" },
        { word: "Breaking Bad", hint: "Pustinja" },
        { word: "Stranger Things", hint: "Naopako" },
        { word: "Game of Thrones", hint: "Presto" },
        { word: "Friends", hint: "Kafić" },
        { word: "The Office", hint: "Papir" },
        { word: "Squid Game", hint: "Maska" },
        { word: "Peaky Blinders", hint: "Kačket" },
        { word: "Money Heist", hint: "Kombinezon" },
        { word: "The Witcher", hint: "Medaljon" },
        { word: "John Wick", hint: "Olovka" },
        { word: "Fast and Furious", hint: "Menjač" },
        { word: "Rocky", hint: "Stepenice" },
        { word: "Interstellar", hint: "Crna rupa" },
        { word: "Jurassic Park", hint: "Komarci" },
        { word: "Pirates of Caribbean", hint: "Kompas" },
        { word: "Home Alone", hint: "Zamke" },
        { word: "Mr. Bean", hint: "Mečka" },
        { word: "Tom i Jerry", hint: "Jurnjava" },
        { word: "Spongebob", hint: "Sunđer" },
        { word: "Naruto", hint: "Senka" },
        { word: "One Piece", hint: "Blago" },
        { word: "Attack on Titan", hint: "Zidovi" },
        { word: "The Simpsons", hint: "Žuto" },
        { word: "South Park", hint: "Sneg" },
        { word: "Rick and Morty", hint: "Portal" },
        { word: "Dune", hint: "Pesak" },
        { word: "Avatar", hint: "Plavo" },
        { word: "The Godfather", hint: "Ponuda" },
        { word: "Inception", hint: "Fijuk" },
        { word: "Venom", hint: "Crna masa" },
        { word: "Cars", hint: "Staza" },
        { word: "Up", hint: "Baloni" },
        { word: "Zootopia", hint: "Dosije" },
        { word: "Wednesday", hint: "Pletenice" }
    ]
};

export const muzika = {
    category: "Muzika",
    items: [
        { word: "Gitara", hint: "Žica" },
        { word: "Bubnjevi", hint: "Palice" },
        { word: "Klavir", hint: "Dirke" },
        { word: "Violina", hint: "Gudalo" },
        { word: "Flauta", hint: "Dah" },
        { word: "Truba", hint: "Fanfare" },
        { word: "Harmonika", hint: "Meh" },
        { word: "Saksofon", hint: "Dimnjak" },
        { word: "Ukulele", hint: "Ostrvo" },
        { word: "Rok", hint: "Buntovnik" },
        { word: "Pop", hint: "Mainstream" },
        { word: "Hip-hop", hint: "Rime" },
        { word: "Džez", hint: "Improvizacija" },
        { word: "Turbo-folk", hint: "Kafana" },
        { word: "Tehno", hint: "Stroboskop" },
        { word: "Reggae", hint: "Dredovi" },
        { word: "Opera", hint: "Ložava" },
        { word: "DJ", hint: "Ploča" },
        { word: "Refren", hint: "Ponavljanje" },
        { word: "Hor", hint: "Masa" },
        { word: "Album", hint: "Kolekcija" },
        { word: "Vinilna ploča", hint: "Igla" },
        { word: "Karaoke", hint: "Ekran" },
        { word: "Festival", hint: "Bina" },
        { word: "EXIT", hint: "Tvrđava" },
        { word: "Eurovision", hint: "Dvanaest" },
        { word: "Grammy", hint: "Gramofon" },
        { word: "Nota", hint: "Crtovlje" },
        { word: "Melodija", hint: "Zvižd" },
        { word: "Bas", hint: "Vibracija" },
        { word: "Remix", hint: "Verzija" },
        { word: "Playlist", hint: "Redosled" },
        { word: "Himna", hint: "Stajanje" },
        { word: "Balada", hint: "Tuga" },
        { word: "Punk", hint: "Irokezija" },
        { word: "R&B", hint: "Duša" },
        { word: "Metal", hint: "Kosa" },
        { word: "Trance", hint: "Trans" },
        { word: "Koncert", hint: "Publika" },
        { word: "Metronom", hint: "Otkucaj" },
        { word: "Solo", hint: "Reflektora" },
        { word: "Akord", hint: "Hvat" },
        { word: "Tekst pesme", hint: "Stihovi" },
        { word: "Bend", hint: "Garaža" },
        { word: "Guča", hint: "Trubljači" },
        { word: "Singl", hint: "Premijera" },
        { word: "Zvučnik", hint: "Membrana" },
        { word: "Riff", hint: "Ponavljanje" },
        { word: "Tamburica", hint: "Vojvodina" },
        { word: "Serenada", hint: "Balkon" }
    ]
};

export const geografija = {
    category: "Geografija",
    items: [
        { word: "Pariz", hint: "Kroasan" },
        { word: "Beograd", hint: "Ušće" },
        { word: "Njujork", hint: "Taksi" },
        { word: "Tokio", hint: "Neon" },
        { word: "Rim", hint: "Fontana" },
        { word: "Berlin", hint: "Zid" },
        { word: "Istanbul", hint: "Čaršija" },
        { word: "Moskva", hint: "Kupola" },
        { word: "Barselona", hint: "Mozaik" },
        { word: "Dubai", hint: "Zlato" },
        { word: "Nil", hint: "Faraon" },
        { word: "Dunav", hint: "Valcer" },
        { word: "Everest", hint: "Zastava" },
        { word: "Sahara", hint: "Fatamorgana" },
        { word: "Atlantik", hint: "Talasi" },
        { word: "Alpi", hint: "Vrh" },
        { word: "Vulkan", hint: "Lava" },
        { word: "Ostrvo", hint: "Izolacija" },
        { word: "Ekvator", hint: "Pojas" },
        { word: "Severni pol", hint: "Kompas" },
        { word: "Grand kanjon", hint: "Provalija" },
        { word: "Ajfelov toranj", hint: "Čelik" },
        { word: "Koloseum", hint: "Ruševina" },
        { word: "Kineski zid", hint: "Granica" },
        { word: "Statua slobode", hint: "Baklja" },
        { word: "Tadž Mahal", hint: "Mermer" },
        { word: "Australija", hint: "Kontinent" },
        { word: "Brazil", hint: "Karneval" },
        { word: "Japan", hint: "Cvet trešnje" },
        { word: "Indija", hint: "Začini" },
        { word: "Niagara", hint: "Bure" },
        { word: "Kopaonik", hint: "Staza" },
        { word: "Tara", hint: "Kanjon" },
        { word: "Novi Sad", hint: "Most" },
        { word: "Venecija", hint: "Kanal" },
        { word: "Prag", hint: "Sat" },
        { word: "Singapur", hint: "Strogost" },
        { word: "Santorini", hint: "Krater" },
        { word: "Havaji", hint: "Ogrlica" },
        { word: "Antarktik", hint: "Belo" },
        { word: "Amazonija", hint: "Pluća" },
        { word: "Mediteran", hint: "Masline" },
        { word: "Maldivi", hint: "Bungalov" },
        { word: "London", hint: "Magla" },
        { word: "Amsterdam", hint: "Kanal" },
        { word: "Budimpešta", hint: "Banja" },
        { word: "Lisabon", hint: "Tramvaj" },
        { word: "Egipat", hint: "Piramida" },
        { word: "Grenland", hint: "Ledenjak" },
        { word: "Island", hint: "Gejzir" }
    ]
};

export const zanimanja = {
    category: "Zanimanja",
    items: [
        { word: "Doktor", hint: "Stetoskop" },
        { word: "Advokat", hint: "Toga" },
        { word: "Učitelj", hint: "Tabla" },
        { word: "Policajac", hint: "Značka" },
        { word: "Kuvar", hint: "Bela kapa" },
        { word: "Pilot", hint: "Kokpit" },
        { word: "Vojnik", hint: "Uniforma" },
        { word: "Programer", hint: "Konzola" },
        { word: "Novinar", hint: "Ekskluziva" },
        { word: "Glumac", hint: "Maska" },
        { word: "Frizer", hint: "Ogledalo" },
        { word: "Stolar", hint: "Šavovi" },
        { word: "Mehaničar", hint: "Ulje" },
        { word: "Električar", hint: "Struja" },
        { word: "Vodoinstalater", hint: "Cev" },
        { word: "Farmer", hint: "Njiva" },
        { word: "Astronaut", hint: "Orbita" },
        { word: "Taksista", hint: "Taksimetar" },
        { word: "Kapetan", hint: "Kormilo" },
        { word: "Pisac", hint: "Mastilo" },
        { word: "Bibliotekar", hint: "Tišina" },
        { word: "Fotograf", hint: "Blic" },
        { word: "Arhitekta", hint: "Nacrt" },
        { word: "Hirurg", hint: "Skalpel" },
        { word: "Zubar", hint: "Stolica" },
        { word: "Veterinar", hint: "Šapa" },
        { word: "Apotekar", hint: "Recept" },
        { word: "Menadžer", hint: "Prezentacija" },
        { word: "Detektiv", hint: "Lupa" },
        { word: "Prevodilac", hint: "Rečnik" },
        { word: "Poštar", hint: "Pismo" },
        { word: "Konobar", hint: "Tacna" },
        { word: "DJ", hint: "Mikseta" },
        { word: "Influenser", hint: "Pratilac" },
        { word: "Komičar", hint: "Tajming" },
        { word: "Mađioničar", hint: "Cilindar" },
        { word: "Moler", hint: "Valjak" },
        { word: "Krojač", hint: "Metar" },
        { word: "Portir", hint: "Kapija" },
        { word: "Arheolog", hint: "Iskopina" },
        { word: "Psiholog", hint: "Kauč" },
        { word: "Sudija", hint: "Čekić" },
        { word: "Vatrogasac", hint: "Merdevine" },
        { word: "Dimničar", hint: "Čađ" },
        { word: "Spasalac", hint: "Zvižduk" },
        { word: "Kaskader", hint: "Dupla" },
        { word: "Pekar", hint: "Zora" },
        { word: "Kondukter", hint: "Karta" },
        { word: "Barmen", hint: "Šejker" },
        { word: "Geolog", hint: "Slojevi" }
    ]
};

export const vozila = {
    category: "Vozila i prevoz",
    items: [
        { word: "Automobil", hint: "Volant" },
        { word: "Autobus", hint: "Stanica" },
        { word: "Voz", hint: "Pruga" },
        { word: "Avion", hint: "Turbulencija" },
        { word: "Brod", hint: "Paluba" },
        { word: "Motor", hint: "Kaciga" },
        { word: "Bicikl", hint: "Pedala" },
        { word: "Kamion", hint: "Rikverc" },
        { word: "Taksi", hint: "Žuta" },
        { word: "Ambulanta", hint: "Sirena" },
        { word: "Policijski auto", hint: "Rotacija" },
        { word: "Bager", hint: "Kašika" },
        { word: "Traktor", hint: "Brazda" },
        { word: "Džip", hint: "Teren" },
        { word: "Metro", hint: "Tunel" },
        { word: "Jedrilica", hint: "Vetar" },
        { word: "Kajak", hint: "Brzak" },
        { word: "Podmornica", hint: "Periskop" },
        { word: "Raketa", hint: "Odbrojavanje" },
        { word: "Balon", hint: "Korpa" },
        { word: "Gondola", hint: "Visina" },
        { word: "Sanke", hint: "Nizbrdica" },
        { word: "Tenk", hint: "Oklop" },
        { word: "Sportski auto", hint: "Šesd" },
        { word: "Limuzina", hint: "Luksuz" },
        { word: "Kabriolet", hint: "Krov" },
        { word: "Tesla", hint: "Autopilot" },
        { word: "Ferrari", hint: "Konj" },
        { word: "Lamborghini", hint: "Bik" },
        { word: "Fiat", hint: "Punto" },
        { word: "Volkswagen", hint: "Buba" },
        { word: "Toyota", hint: "Hibrid" },
        { word: "Harley Davidson", hint: "Tutnjava" },
        { word: "Vespa", hint: "Nostalgiija" },
        { word: "Gliser", hint: "Pena" },
        { word: "Jet ski", hint: "Obale" },
        { word: "Kruzer", hint: "Palata" },
        { word: "Rikša", hint: "Pedala" },
        { word: "Kočija", hint: "Uzde" },
        { word: "Helikopter", hint: "Rotor" },
        { word: "Tramvaj", hint: "Šine" },
        { word: "Trolejbus", hint: "Žica" },
        { word: "Trotinet", hint: "Guranje" },
        { word: "Segvej", hint: "Ravnoteža" },
        { word: "Katamaran", hint: "Dva trupa" },
        { word: "Cepelin", hint: "Helijum" },
        { word: "Kombajn", hint: "Žetva" },
        { word: "Rolšue", hint: "Asfalt" },
        { word: "Skejtbord", hint: "Trik" },
        { word: "Dron", hint: "Snimak" }
    ]
};

export const predmeti = {
    category: "Svakodnevni predmeti",
    items: [
        { word: "Stolica", hint: "Naslon" },
        { word: "Sto", hint: "Površina" },
        { word: "Krevet", hint: "Dušek" },
        { word: "Ormar", hint: "Vešalica" },
        { word: "Ogledalo", hint: "Odraz" },
        { word: "Kišobran", hint: "Drška" },
        { word: "Sat", hint: "Kazaljka" },
        { word: "Naočare", hint: "Dioptrija" },
        { word: "Novčanik", hint: "Džep" },
        { word: "Ključ", hint: "Brava" },
        { word: "Olovka", hint: "Grafit" },
        { word: "Sveska", hint: "Margin" },
        { word: "Knjiga", hint: "Obeležavač" },
        { word: "Lampa", hint: "Sijalica" },
        { word: "Tepih", hint: "Letenje" },
        { word: "Zavesa", hint: "Draperija" },
        { word: "Jastuk", hint: "Perje" },
        { word: "Peškir", hint: "Pamuk" },
        { word: "Sapun", hint: "Pena" },
        { word: "Četkica za zube", hint: "Pasta" },
        { word: "Fen", hint: "Mlaznica" },
        { word: "Makaze", hint: "Sečivo" },
        { word: "Čekić", hint: "Ekser" },
        { word: "Metla", hint: "Prut" },
        { word: "Pegla", hint: "Para" },
        { word: "Veš mašina", hint: "Bubanj" },
        { word: "Frižider", hint: "Magnet" },
        { word: "Šporet", hint: "Ringla" },
        { word: "Tanjir", hint: "Glina" },
        { word: "Šolja", hint: "Drška" },
        { word: "Kašika", hint: "Udubljenje" },
        { word: "Tiganj", hint: "Premaz" },
        { word: "Ventilator", hint: "Lopatice" },
        { word: "Daljinski", hint: "Kanal" },
        { word: "Ranac", hint: "Leđa" },
        { word: "Patike", hint: "Pertla" },
        { word: "Kapa", hint: "Vizir" },
        { word: "Jakna", hint: "Rajsferšlus" },
        { word: "Šal", hint: "Vuna" },
        { word: "Rukavice", hint: "Prsti" },
        { word: "Upaljač", hint: "Plamen" },
        { word: "Sveća", hint: "Fitilj" },
        { word: "Alarm", hint: "Buđenje" },
        { word: "Nož", hint: "Oštrica" },
        { word: "Viljuška", hint: "Zupci" },
        { word: "Bojler", hint: "Kapljica" },
        { word: "Usisivač", hint: "Prašina" },
        { word: "Gumica", hint: "Brisanje" },
        { word: "Lenjir", hint: "Centimetar" },
        { word: "Baterija", hint: "Plus" }
    ]
};

export const igreIZabava = {
    category: "Igre i zabava",
    items: [
        { word: "Monopol", hint: "Ulica" },
        { word: "Čovče ne ljuti se", hint: "Izbacivanje" },
        { word: "Karte", hint: "Špil" },
        { word: "Uno", hint: "Poslednja" },
        { word: "Jenga", hint: "Kula" },
        { word: "Sudoku", hint: "Mreža" },
        { word: "Scrabble", hint: "Bodovi" },
        { word: "Slagalica", hint: "Uklapanje" },
        { word: "Tetris", hint: "Obrtaj" },
        { word: "Minecraft", hint: "Kocka" },
        { word: "Fortnite", hint: "Krug" },
        { word: "GTA", hint: "Mapa" },
        { word: "FIFA", hint: "Režim" },
        { word: "Counter-Strike", hint: "Bomba" },
        { word: "Mario", hint: "Pečurka" },
        { word: "Pac-Man", hint: "Lavirint" },
        { word: "League of Legends", hint: "Linija" },
        { word: "Among Us", hint: "Sumnjiv" },
        { word: "Escape room", hint: "Ključ" },
        { word: "Paintball", hint: "Vizir" },
        { word: "Laser tag", hint: "Senzor" },
        { word: "Go-kart", hint: "Krivina" },
        { word: "Tobogan", hint: "Klizanje" },
        { word: "Ringišpil", hint: "Točak" },
        { word: "Fliper", hint: "Kuglica" },
        { word: "Karaoke", hint: "Ekran" },
        { word: "Stand-up", hint: "Mikrofon" },
        { word: "Cirkus", hint: "Šator" },
        { word: "Bioskop", hint: "Kokice" },
        { word: "Akva park", hint: "Tobogan" },
        { word: "ZOO vrt", hint: "Kavez" },
        { word: "Truth or Dare", hint: "Boca" },
        { word: "Pikado", hint: "Centar" },
        { word: "Klikeri", hint: "Stakleni" },
        { word: "Yo-yo", hint: "Kanap" },
        { word: "Zmaj", hint: "Vetar" },
        { word: "Bazen", hint: "Hlor" },
        { word: "Sauna", hint: "Peškir" },
        { word: "Tombola", hint: "Brojevi" },
        { word: "Poker", hint: "Blef" },
        { word: "Šah", hint: "Mat" },
        { word: "Risk", hint: "Teritorija" },
        { word: "Vrtuljak", hint: "Konjić" },
        { word: "Trampolina", hint: "Odskok" },
        { word: "Luna park", hint: "Svetla" },
        { word: "Bumerang", hint: "Povratak" },
        { word: "Frisbee", hint: "Disk" },
        { word: "Hulahop", hint: "Struk" },
        { word: "Rubikova kocka", hint: "Boje" },
        { word: "Call of Duty", hint: "Misija" }
    ]
};

export default [tehnologija, hranaIPice, zivotinje, sport, filmoviISerije, muzika, geografija, zanimanja, vozila, predmeti, igreIZabava];
