export const zivotinjeOstatak = {
    category: "Životinje 2",
    items: [
        { word: "Hijena", hint: "Divlji pas" },
        { word: "Leopard", hint: "Gepard" },
        { word: "Lemur", hint: "Rakun" },
        { word: "Vidra", hint: "Dabar" },
        { word: "Tukan", hint: "Flamingo" },
        { word: "Fazan", hint: "Paun" },
        { word: "Skakavac", hint: "Cvrčak" },
        { word: "Bubamara", hint: "Svitac" },
        { word: "Morž", hint: "Foka" },
        { word: "Morski konjic", hint: "Morska zvezda" },
        { word: "Glista", hint: "Pijavica" },
        { word: "Slepi miš", hint: "Sova" },
        { word: "Koala", hint: "Lenjivac" },
        { word: "Bubašvaba", hint: "Buba maru" },
        { word: "Gavijal", hint: "Kajman" },
        { word: "Mrmot", hint: "Krtica" },
        { word: "Kobac", hint: "Lešinar" },
        { word: "Golub", hint: "Grlica" },
        { word: "Tvor", hint: "Mungos" },
        { word: "Džukela", hint: "Hrt" },
        { word: "Triton", hint: "Daždevnjak" },
        { word: "Medúza", hint: "Anemona" },
        { word: "Kit ajkula", hint: "Raža" },
        { word: "Puma", hint: "Ris" },
        { word: "Jak", hint: "Gnu" },
        { word: "Mravojed", hint: "Armadilo" },
        { word: "Kameleon", hint: "Iguana" },
        { word: "Vrabac", hint: "Lastavica" },
        { word: "Detlić", hint: "Kukavica" },
        { word: "Sršen", hint: "Bumbar" },
        { word: "Krab", hint: "Kozica" },
        { word: "Jegulja", hint: "Zmija" },
        { word: "Galeb", hint: "Albatros" },
        { word: "Okap", hint: "Antilopa" },
        { word: "Jakare", hint: "Garijal" },
        { word: "Zeba", hint: "Štiglić" },
        { word: "Sokoko", hint: "Kokoška" },
        { word: "Suri orao", hint: "Beloglavi sup" },
        { word: "Grizli", hint: "Beli medved" },
        { word: "Hrčak", hint: "Gerbil" },
        { word: "Činčila", hint: "Zamorac" },
        { word: "Mungo", hint: "Lasica" },
        { word: "Morski lav", hint: "Morski slon" },
        { word: "Barakuda", hint: "Piranha" },
        { word: "Pastrmka", hint: "Šaran" },
        { word: "Som", hint: "Štuka" },
        { word: "Tuna", hint: "Losos" },
        { word: "Morski pas", hint: "Kit" },
        { word: "Mungos", hint: "Vidra" },
        { word: "Kuna", hint: "Samur" },
        { word: "Kojot", hint: "Vuk" },
        { word: "Bufalo", hint: "Bizon" },
        { word: "Nosati rakun", hint: "Rakun" },
        { word: "Vombat", hint: "Kvoka" },
        { word: "Emu", hint: "Kazuari" },
        { word: "Drozd", hint: "Kos" },
        { word: "Siva čaplja", hint: "Roda" },
        { word: "Kormoran", hint: "Gnjurac" },
        { word: "Sipa", hint: "Nautilus" },
        { word: "Bogomoljka", hint: "Insekt list" }
    ]
};

export default [zivotinjeOstatak];
